title: "Aditya Attrey"
description: "Aerospace engineering student — projects, write-ups, and things I'm learning."
url: "https://adityaattrey.com"   # ← change to your GitHub Pages URL
baseurl: ""                             # ← leave empty if using yourusername.github.io
                                         #   set to "/repo-name" if using a project repo

author:
  name: "Aditya Attrey"
  email: "aditya.attrey@gmail.com"
  github: "FBRDCYB3R"
  linkedin: "aditya-attrey"
stats:
  year: "2nd"
  launches: 11680 

# Jekyll settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:slug/


# Collections
collections:
  projects: 
    output: true
    permalink: /projects/:slug/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
